name: Build and Deploy Logic App. 

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Create project folder
        run: |
          mkdir output
          cp 'host.json' 'output/'
          cp -r 'NewWorkflow' 'output/'
          cp -r 'IntegrateWorkflow' 'output/'
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: build-art/${{ github.run_id }}.zip
          files: output/
      - uses: actions/upload-artifact@master
        with:
          name: build-artefact
          path: build-art/


  DeployStaging:
    name: Deploy to Staging
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:
    - uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Get publish Profile
      id: laapp
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ secrets.RG_LA }} `
              -Name ${{ secrets.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest
        
    - uses: actions/download-artifact@master
      with:
        name: build-artefact
        path: build-art/
        
    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1
      id: la
      with:
        app-name: ${{secrets.RG_LA}}
        package: build-art/${{ github.run_id }}.zip
        publish-profile: ${{steps.laapp.outputs.profile}}
        
      
  DeployProduction:
    name: Deploy to Prod 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
    - uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Get publish Profile
      id: laarcapp
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ secrets.RG_LA }} `
              -Name ${{ secrets.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest
    - uses: actions/download-artifact@master
      with:
        name: build-artefact
        path: build-art/
    - name: Deploy to Azure Arc enabled Logic App
      uses: Azure/functions-action@v1
      id: arcla
      with:
        app-name: ${{secrets.RG_LA}}
        package: build-art/${{ github.run_id }}.zip
        publish-profile: ${{steps.laarcapp.outputs.profile}}
