name: Build and Deploy Logic App. 

env:
  RG_LA: 'blylima3'
  LA_NAME: 'bugbashdemo'

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Compile
        run: echo Hello, world!
          
      - name: Create project folder
        run: |
          mkdir output
          cp 'host.json' 'output/'
          cp -r 'NewWorkflow' 'output/'
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: '${{ github.run_id }}.zip'
          files: output/

        
  DeployStaging:
    name: Deploy to Staging
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Get publish Profile
      id: fncapp
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ env.RG_LA }} `
              -Name ${{ env.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{env.RG_LA}}
        package: '${{ github.run_id }}.zip'
        publish-profile: ${{steps.fncapp.outputs.profile}}
        
  DeployProduction:
    name: Deploy to Prod 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Get publish Profile
      id: fncapp
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ env.RG_LA }} `
              -Name ${{ env.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{env.RG_LA}}
        package: '${{ github.run_id }}.zip'
        publish-profile: ${{steps.fncapp.outputs.profile}}
